/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVisualGroundingSettingsIndexRouteImport } from './routes/_authenticated/visual-grounding-settings/index'
import { Route as AuthenticatedVisualGroundingActivityIndexRouteImport } from './routes/_authenticated/visual-grounding-activity/index'
import { Route as AuthenticatedVectorSettingsIndexRouteImport } from './routes/_authenticated/vector-settings/index'
import { Route as AuthenticatedVectorReferencesIndexRouteImport } from './routes/_authenticated/vector-references/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUserGroupsIndexRouteImport } from './routes/_authenticated/user-groups/index'
import { Route as AuthenticatedUrlDownloadsIndexRouteImport } from './routes/_authenticated/url-downloads/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSearchApiIndexRouteImport } from './routes/_authenticated/search-api/index'
import { Route as AuthenticatedResetRequestsIndexRouteImport } from './routes/_authenticated/reset-requests/index'
import { Route as AuthenticatedResetDataIndexRouteImport } from './routes/_authenticated/reset-data/index'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers/index'
import { Route as AuthenticatedPromptsIndexRouteImport } from './routes/_authenticated/prompts/index'
import { Route as AuthenticatedOcrSettingsIndexRouteImport } from './routes/_authenticated/ocr-settings/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedMessageHistoryIndexRouteImport } from './routes/_authenticated/message-history/index'
import { Route as AuthenticatedLogoSettingsIndexRouteImport } from './routes/_authenticated/logo-settings/index'
import { Route as AuthenticatedLibrariesIndexRouteImport } from './routes/_authenticated/libraries/index'
import { Route as AuthenticatedLanguagesIndexRouteImport } from './routes/_authenticated/languages/index'
import { Route as AuthenticatedKnowledgesIndexRouteImport } from './routes/_authenticated/knowledges/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFolderUploadIndexRouteImport } from './routes/_authenticated/folder-upload/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback/index'
import { Route as AuthenticatedEmbeddingModelsIndexRouteImport } from './routes/_authenticated/embedding-models/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedChangePasswordIndexRouteImport } from './routes/_authenticated/change-password/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedCatalogsIndexRouteImport } from './routes/_authenticated/catalogs/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/app-settings/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisualGroundingSettingsIndexRoute =
  AuthenticatedVisualGroundingSettingsIndexRouteImport.update({
    id: '/visual-grounding-settings/',
    path: '/visual-grounding-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisualGroundingActivityIndexRoute =
  AuthenticatedVisualGroundingActivityIndexRouteImport.update({
    id: '/visual-grounding-activity/',
    path: '/visual-grounding-activity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVectorSettingsIndexRoute =
  AuthenticatedVectorSettingsIndexRouteImport.update({
    id: '/vector-settings/',
    path: '/vector-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVectorReferencesIndexRoute =
  AuthenticatedVectorReferencesIndexRouteImport.update({
    id: '/vector-references/',
    path: '/vector-references/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserGroupsIndexRoute =
  AuthenticatedUserGroupsIndexRouteImport.update({
    id: '/user-groups/',
    path: '/user-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUrlDownloadsIndexRoute =
  AuthenticatedUrlDownloadsIndexRouteImport.update({
    id: '/url-downloads/',
    path: '/url-downloads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSearchApiIndexRoute =
  AuthenticatedSearchApiIndexRouteImport.update({
    id: '/search-api/',
    path: '/search-api/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResetRequestsIndexRoute =
  AuthenticatedResetRequestsIndexRouteImport.update({
    id: '/reset-requests/',
    path: '/reset-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResetDataIndexRoute =
  AuthenticatedResetDataIndexRouteImport.update({
    id: '/reset-data/',
    path: '/reset-data/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromptsIndexRoute =
  AuthenticatedPromptsIndexRouteImport.update({
    id: '/prompts/',
    path: '/prompts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcrSettingsIndexRoute =
  AuthenticatedOcrSettingsIndexRouteImport.update({
    id: '/ocr-settings/',
    path: '/ocr-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessageHistoryIndexRoute =
  AuthenticatedMessageHistoryIndexRouteImport.update({
    id: '/message-history/',
    path: '/message-history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogoSettingsIndexRoute =
  AuthenticatedLogoSettingsIndexRouteImport.update({
    id: '/logo-settings/',
    path: '/logo-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibrariesIndexRoute =
  AuthenticatedLibrariesIndexRouteImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLanguagesIndexRoute =
  AuthenticatedLanguagesIndexRouteImport.update({
    id: '/languages/',
    path: '/languages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgesIndexRoute =
  AuthenticatedKnowledgesIndexRouteImport.update({
    id: '/knowledges/',
    path: '/knowledges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFolderUploadIndexRoute =
  AuthenticatedFolderUploadIndexRouteImport.update({
    id: '/folder-upload/',
    path: '/folder-upload/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmbeddingModelsIndexRoute =
  AuthenticatedEmbeddingModelsIndexRouteImport.update({
    id: '/embedding-models/',
    path: '/embedding-models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordIndexRoute =
  AuthenticatedChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogsIndexRoute =
  AuthenticatedCatalogsIndexRouteImport.update({
    id: '/catalogs/',
    path: '/catalogs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/app-settings/',
    path: '/app-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/app-settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/change-password/': typeof AuthenticatedChangePasswordIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/embedding-models/': typeof AuthenticatedEmbeddingModelsIndexRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/files/': typeof AuthenticatedFilesIndexRoute
  '/folder-upload/': typeof AuthenticatedFolderUploadIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/knowledges/': typeof AuthenticatedKnowledgesIndexRoute
  '/languages/': typeof AuthenticatedLanguagesIndexRoute
  '/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/logo-settings/': typeof AuthenticatedLogoSettingsIndexRoute
  '/message-history/': typeof AuthenticatedMessageHistoryIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/ocr-settings/': typeof AuthenticatedOcrSettingsIndexRoute
  '/prompts/': typeof AuthenticatedPromptsIndexRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/reset-data/': typeof AuthenticatedResetDataIndexRoute
  '/reset-requests/': typeof AuthenticatedResetRequestsIndexRoute
  '/search-api/': typeof AuthenticatedSearchApiIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/url-downloads/': typeof AuthenticatedUrlDownloadsIndexRoute
  '/user-groups/': typeof AuthenticatedUserGroupsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/vector-references/': typeof AuthenticatedVectorReferencesIndexRoute
  '/vector-settings/': typeof AuthenticatedVectorSettingsIndexRoute
  '/visual-grounding-activity/': typeof AuthenticatedVisualGroundingActivityIndexRoute
  '/visual-grounding-settings/': typeof AuthenticatedVisualGroundingSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/app-settings': typeof AuthenticatedAppSettingsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/catalogs': typeof AuthenticatedCatalogsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/change-password': typeof AuthenticatedChangePasswordIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/embedding-models': typeof AuthenticatedEmbeddingModelsIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/folder-upload': typeof AuthenticatedFolderUploadIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/knowledges': typeof AuthenticatedKnowledgesIndexRoute
  '/languages': typeof AuthenticatedLanguagesIndexRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/logo-settings': typeof AuthenticatedLogoSettingsIndexRoute
  '/message-history': typeof AuthenticatedMessageHistoryIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/ocr-settings': typeof AuthenticatedOcrSettingsIndexRoute
  '/prompts': typeof AuthenticatedPromptsIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/reset-data': typeof AuthenticatedResetDataIndexRoute
  '/reset-requests': typeof AuthenticatedResetRequestsIndexRoute
  '/search-api': typeof AuthenticatedSearchApiIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/url-downloads': typeof AuthenticatedUrlDownloadsIndexRoute
  '/user-groups': typeof AuthenticatedUserGroupsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vector-references': typeof AuthenticatedVectorReferencesIndexRoute
  '/vector-settings': typeof AuthenticatedVectorSettingsIndexRoute
  '/visual-grounding-activity': typeof AuthenticatedVisualGroundingActivityIndexRoute
  '/visual-grounding-settings': typeof AuthenticatedVisualGroundingSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/app-settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/change-password/': typeof AuthenticatedChangePasswordIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/embedding-models/': typeof AuthenticatedEmbeddingModelsIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/folder-upload/': typeof AuthenticatedFolderUploadIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/knowledges/': typeof AuthenticatedKnowledgesIndexRoute
  '/_authenticated/languages/': typeof AuthenticatedLanguagesIndexRoute
  '/_authenticated/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/_authenticated/logo-settings/': typeof AuthenticatedLogoSettingsIndexRoute
  '/_authenticated/message-history/': typeof AuthenticatedMessageHistoryIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/ocr-settings/': typeof AuthenticatedOcrSettingsIndexRoute
  '/_authenticated/prompts/': typeof AuthenticatedPromptsIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/reset-data/': typeof AuthenticatedResetDataIndexRoute
  '/_authenticated/reset-requests/': typeof AuthenticatedResetRequestsIndexRoute
  '/_authenticated/search-api/': typeof AuthenticatedSearchApiIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/url-downloads/': typeof AuthenticatedUrlDownloadsIndexRoute
  '/_authenticated/user-groups/': typeof AuthenticatedUserGroupsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vector-references/': typeof AuthenticatedVectorReferencesIndexRoute
  '/_authenticated/vector-settings/': typeof AuthenticatedVectorSettingsIndexRoute
  '/_authenticated/visual-grounding-activity/': typeof AuthenticatedVisualGroundingActivityIndexRoute
  '/_authenticated/visual-grounding-settings/': typeof AuthenticatedVisualGroundingSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/app-settings/'
    | '/apps/'
    | '/catalogs/'
    | '/categories/'
    | '/change-password/'
    | '/chats/'
    | '/embedding-models/'
    | '/feedback/'
    | '/files/'
    | '/folder-upload/'
    | '/help-center/'
    | '/knowledges/'
    | '/languages/'
    | '/libraries/'
    | '/logo-settings/'
    | '/message-history/'
    | '/models/'
    | '/ocr-settings/'
    | '/prompts/'
    | '/providers/'
    | '/reset-data/'
    | '/reset-requests/'
    | '/search-api/'
    | '/settings/'
    | '/tasks/'
    | '/url-downloads/'
    | '/user-groups/'
    | '/users/'
    | '/vector-references/'
    | '/vector-settings/'
    | '/visual-grounding-activity/'
    | '/visual-grounding-settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/app-settings'
    | '/apps'
    | '/catalogs'
    | '/categories'
    | '/change-password'
    | '/chats'
    | '/embedding-models'
    | '/feedback'
    | '/files'
    | '/folder-upload'
    | '/help-center'
    | '/knowledges'
    | '/languages'
    | '/libraries'
    | '/logo-settings'
    | '/message-history'
    | '/models'
    | '/ocr-settings'
    | '/prompts'
    | '/providers'
    | '/reset-data'
    | '/reset-requests'
    | '/search-api'
    | '/settings'
    | '/tasks'
    | '/url-downloads'
    | '/user-groups'
    | '/users'
    | '/vector-references'
    | '/vector-settings'
    | '/visual-grounding-activity'
    | '/visual-grounding-settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/app-settings/'
    | '/_authenticated/apps/'
    | '/_authenticated/catalogs/'
    | '/_authenticated/categories/'
    | '/_authenticated/change-password/'
    | '/_authenticated/chats/'
    | '/_authenticated/embedding-models/'
    | '/_authenticated/feedback/'
    | '/_authenticated/files/'
    | '/_authenticated/folder-upload/'
    | '/_authenticated/help-center/'
    | '/_authenticated/knowledges/'
    | '/_authenticated/languages/'
    | '/_authenticated/libraries/'
    | '/_authenticated/logo-settings/'
    | '/_authenticated/message-history/'
    | '/_authenticated/models/'
    | '/_authenticated/ocr-settings/'
    | '/_authenticated/prompts/'
    | '/_authenticated/providers/'
    | '/_authenticated/reset-data/'
    | '/_authenticated/reset-requests/'
    | '/_authenticated/search-api/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/url-downloads/'
    | '/_authenticated/user-groups/'
    | '/_authenticated/users/'
    | '/_authenticated/vector-references/'
    | '/_authenticated/vector-settings/'
    | '/_authenticated/visual-grounding-activity/'
    | '/_authenticated/visual-grounding-settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visual-grounding-settings/': {
      id: '/_authenticated/visual-grounding-settings/'
      path: '/visual-grounding-settings'
      fullPath: '/visual-grounding-settings/'
      preLoaderRoute: typeof AuthenticatedVisualGroundingSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visual-grounding-activity/': {
      id: '/_authenticated/visual-grounding-activity/'
      path: '/visual-grounding-activity'
      fullPath: '/visual-grounding-activity/'
      preLoaderRoute: typeof AuthenticatedVisualGroundingActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vector-settings/': {
      id: '/_authenticated/vector-settings/'
      path: '/vector-settings'
      fullPath: '/vector-settings/'
      preLoaderRoute: typeof AuthenticatedVectorSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vector-references/': {
      id: '/_authenticated/vector-references/'
      path: '/vector-references'
      fullPath: '/vector-references/'
      preLoaderRoute: typeof AuthenticatedVectorReferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-groups/': {
      id: '/_authenticated/user-groups/'
      path: '/user-groups'
      fullPath: '/user-groups/'
      preLoaderRoute: typeof AuthenticatedUserGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/url-downloads/': {
      id: '/_authenticated/url-downloads/'
      path: '/url-downloads'
      fullPath: '/url-downloads/'
      preLoaderRoute: typeof AuthenticatedUrlDownloadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/search-api/': {
      id: '/_authenticated/search-api/'
      path: '/search-api'
      fullPath: '/search-api/'
      preLoaderRoute: typeof AuthenticatedSearchApiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reset-requests/': {
      id: '/_authenticated/reset-requests/'
      path: '/reset-requests'
      fullPath: '/reset-requests/'
      preLoaderRoute: typeof AuthenticatedResetRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reset-data/': {
      id: '/_authenticated/reset-data/'
      path: '/reset-data'
      fullPath: '/reset-data/'
      preLoaderRoute: typeof AuthenticatedResetDataIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts/': {
      id: '/_authenticated/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof AuthenticatedPromptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocr-settings/': {
      id: '/_authenticated/ocr-settings/'
      path: '/ocr-settings'
      fullPath: '/ocr-settings/'
      preLoaderRoute: typeof AuthenticatedOcrSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/message-history/': {
      id: '/_authenticated/message-history/'
      path: '/message-history'
      fullPath: '/message-history/'
      preLoaderRoute: typeof AuthenticatedMessageHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logo-settings/': {
      id: '/_authenticated/logo-settings/'
      path: '/logo-settings'
      fullPath: '/logo-settings/'
      preLoaderRoute: typeof AuthenticatedLogoSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libraries/': {
      id: '/_authenticated/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof AuthenticatedLibrariesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/languages/': {
      id: '/_authenticated/languages/'
      path: '/languages'
      fullPath: '/languages/'
      preLoaderRoute: typeof AuthenticatedLanguagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledges/': {
      id: '/_authenticated/knowledges/'
      path: '/knowledges'
      fullPath: '/knowledges/'
      preLoaderRoute: typeof AuthenticatedKnowledgesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folder-upload/': {
      id: '/_authenticated/folder-upload/'
      path: '/folder-upload'
      fullPath: '/folder-upload/'
      preLoaderRoute: typeof AuthenticatedFolderUploadIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/embedding-models/': {
      id: '/_authenticated/embedding-models/'
      path: '/embedding-models'
      fullPath: '/embedding-models/'
      preLoaderRoute: typeof AuthenticatedEmbeddingModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password/': {
      id: '/_authenticated/change-password/'
      path: '/change-password'
      fullPath: '/change-password/'
      preLoaderRoute: typeof AuthenticatedChangePasswordIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogs/': {
      id: '/_authenticated/catalogs/'
      path: '/catalogs'
      fullPath: '/catalogs/'
      preLoaderRoute: typeof AuthenticatedCatalogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app-settings/': {
      id: '/_authenticated/app-settings/'
      path: '/app-settings'
      fullPath: '/app-settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCatalogsIndexRoute: typeof AuthenticatedCatalogsIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedChangePasswordIndexRoute: typeof AuthenticatedChangePasswordIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedEmbeddingModelsIndexRoute: typeof AuthenticatedEmbeddingModelsIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedFolderUploadIndexRoute: typeof AuthenticatedFolderUploadIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedKnowledgesIndexRoute: typeof AuthenticatedKnowledgesIndexRoute
  AuthenticatedLanguagesIndexRoute: typeof AuthenticatedLanguagesIndexRoute
  AuthenticatedLibrariesIndexRoute: typeof AuthenticatedLibrariesIndexRoute
  AuthenticatedLogoSettingsIndexRoute: typeof AuthenticatedLogoSettingsIndexRoute
  AuthenticatedMessageHistoryIndexRoute: typeof AuthenticatedMessageHistoryIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedOcrSettingsIndexRoute: typeof AuthenticatedOcrSettingsIndexRoute
  AuthenticatedPromptsIndexRoute: typeof AuthenticatedPromptsIndexRoute
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
  AuthenticatedResetDataIndexRoute: typeof AuthenticatedResetDataIndexRoute
  AuthenticatedResetRequestsIndexRoute: typeof AuthenticatedResetRequestsIndexRoute
  AuthenticatedSearchApiIndexRoute: typeof AuthenticatedSearchApiIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUrlDownloadsIndexRoute: typeof AuthenticatedUrlDownloadsIndexRoute
  AuthenticatedUserGroupsIndexRoute: typeof AuthenticatedUserGroupsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVectorReferencesIndexRoute: typeof AuthenticatedVectorReferencesIndexRoute
  AuthenticatedVectorSettingsIndexRoute: typeof AuthenticatedVectorSettingsIndexRoute
  AuthenticatedVisualGroundingActivityIndexRoute: typeof AuthenticatedVisualGroundingActivityIndexRoute
  AuthenticatedVisualGroundingSettingsIndexRoute: typeof AuthenticatedVisualGroundingSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCatalogsIndexRoute: AuthenticatedCatalogsIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedChangePasswordIndexRoute: AuthenticatedChangePasswordIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedEmbeddingModelsIndexRoute:
    AuthenticatedEmbeddingModelsIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedFolderUploadIndexRoute: AuthenticatedFolderUploadIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedKnowledgesIndexRoute: AuthenticatedKnowledgesIndexRoute,
  AuthenticatedLanguagesIndexRoute: AuthenticatedLanguagesIndexRoute,
  AuthenticatedLibrariesIndexRoute: AuthenticatedLibrariesIndexRoute,
  AuthenticatedLogoSettingsIndexRoute: AuthenticatedLogoSettingsIndexRoute,
  AuthenticatedMessageHistoryIndexRoute: AuthenticatedMessageHistoryIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedOcrSettingsIndexRoute: AuthenticatedOcrSettingsIndexRoute,
  AuthenticatedPromptsIndexRoute: AuthenticatedPromptsIndexRoute,
  AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
  AuthenticatedResetDataIndexRoute: AuthenticatedResetDataIndexRoute,
  AuthenticatedResetRequestsIndexRoute: AuthenticatedResetRequestsIndexRoute,
  AuthenticatedSearchApiIndexRoute: AuthenticatedSearchApiIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUrlDownloadsIndexRoute: AuthenticatedUrlDownloadsIndexRoute,
  AuthenticatedUserGroupsIndexRoute: AuthenticatedUserGroupsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVectorReferencesIndexRoute:
    AuthenticatedVectorReferencesIndexRoute,
  AuthenticatedVectorSettingsIndexRoute: AuthenticatedVectorSettingsIndexRoute,
  AuthenticatedVisualGroundingActivityIndexRoute:
    AuthenticatedVisualGroundingActivityIndexRoute,
  AuthenticatedVisualGroundingSettingsIndexRoute:
    AuthenticatedVisualGroundingSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
