"""Add task_id to folder_upload_jobs

Revision ID: 13063ae5f85f
Revises: 9d3a5b4d0f15
Create Date: 2025-04-30 00:48:27.788124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13063ae5f85f'
down_revision = '9d3a5b4d0f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_upload_jobs', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder_upload_jobs', 'task_id')
    # ### end Alembic commands ###
