"""add embedding_model to knowledges table

Revision ID: 2886c256d61b
Revises: cd507e8c023a
Create Date: 2025-09-10 13:26:33.167525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2886c256d61b'
down_revision = 'cd507e8c023a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the column if it doesn't already exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('knowledges')]
    if 'embedding_model' not in columns:
        op.add_column('knowledges', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledges', 'embedding_model')
    # ### end Alembic commands ###
