"""Add enable_visual_grounding_for_job to FolderUploadJob

Revision ID: 45a07203e903
Revises: d98af8a9b50c
Create Date: 2025-05-16 23:35:38.200525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '45a07203e903'
down_revision = 'd98af8a9b50c'
branch_labels = None
depends_on = None


def _is_sqlite():
    bind = op.get_bind()
    return bind.dialect.name == 'sqlite'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_upload_jobs', sa.Column('enable_visual_grounding_for_job', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))

    # SQLite stores UUIDs as TEXT and does not support ALTER COLUMN TYPE.
    # This operation is only needed for PostgreSQL.
    if not _is_sqlite():
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.alter_column('id',
                                  existing_type=sa.String(),
                                  type_=postgresql.UUID(as_uuid=True),
                                  existing_nullable=False,
                                  nullable=False,
                                  postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _is_sqlite():
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.alter_column('id',
                                  existing_type=postgresql.UUID(as_uuid=True),
                                  type_=sa.String(),
                                  existing_nullable=False,
                                  nullable=False)
    op.drop_column('folder_upload_jobs', 'enable_visual_grounding_for_job')
    # ### end Alembic commands ###
