"""add library_id and knowledge_id to folder_upload_jobs

Revision ID: 96ec8894ea18
Revises: 13063ae5f85f
Create Date: 2025-04-30 20:34:52.589798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision = '96ec8894ea18'
down_revision = '13063ae5f85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    columns = [c['name'] for c in inspector.get_columns('folder_upload_jobs')]

    if 'library_id' not in columns:
        op.add_column('folder_upload_jobs', sa.Column('library_id', sa.Integer(), nullable=True))

    if 'knowledge_id' not in columns:
        op.add_column('folder_upload_jobs', sa.Column('knowledge_id', sa.Integer(), nullable=True))

    foreign_keys = inspector.get_foreign_keys('folder_upload_jobs')

    fk_knowledge_name = 'fk_folder_upload_jobs_knowledge_id'
    fk_library_name = 'fk_folder_upload_jobs_library_id'

    has_fk_to_knowledges = any(
        fk['referred_table'] == 'knowledges' and fk['constrained_columns'] == ['knowledge_id']
        for fk in foreign_keys
    )

    has_fk_to_libraries = any(
        fk['referred_table'] == 'libraries' and fk['constrained_columns'] == ['library_id']
        for fk in foreign_keys
    )

    if bind.dialect.name == 'sqlite':
        with op.batch_alter_table('folder_upload_jobs') as batch_op:
            if not has_fk_to_knowledges:
                batch_op.create_foreign_key(fk_knowledge_name, 'knowledges', ['knowledge_id'], ['id'])
            if not has_fk_to_libraries:
                batch_op.create_foreign_key(fk_library_name, 'libraries', ['library_id'], ['library_id'])
    else:
        if not has_fk_to_knowledges:
            op.create_foreign_key(fk_knowledge_name, 'folder_upload_jobs', 'knowledges', ['knowledge_id'], ['id'])
        if not has_fk_to_libraries:
            op.create_foreign_key(fk_library_name, 'folder_upload_jobs', 'libraries', ['library_id'], ['library_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    fk_knowledge_name = 'fk_folder_upload_jobs_knowledge_id'
    fk_library_name = 'fk_folder_upload_jobs_library_id'

    if bind.dialect.name == 'sqlite':
        with op.batch_alter_table('folder_upload_jobs') as batch_op:
            batch_op.drop_constraint(fk_library_name, type_='foreignkey')
            batch_op.drop_constraint(fk_knowledge_name, type_='foreignkey')
            batch_op.drop_column('knowledge_id')
            batch_op.drop_column('library_id')
    else:
        op.drop_constraint(fk_library_name, 'folder_upload_jobs', type_='foreignkey')
        op.drop_constraint(fk_knowledge_name, 'folder_upload_jobs', type_='foreignkey')
        op.drop_column('folder_upload_jobs', 'knowledge_id')
        op.drop_column('folder_upload_jobs', 'library_id')
    # ### end Alembic commands ###
