"""Added task_logs table

Revision ID: 9d3a5b4d0f15
Revises: d1f95c33c0c1
Create Date: 2025-04-29 18:27:57.911835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d3a5b4d0f15'
down_revision = 'd1f95c33c0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL with CASCADE to handle dependencies
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('DROP TABLE IF EXISTS langchain_pg_embedding CASCADE;')
        op.execute('DROP TABLE IF EXISTS langchain_pg_collection CASCADE;')
    else:
        op.execute('DROP TABLE IF EXISTS langchain_pg_embedding;')
        op.execute('DROP TABLE IF EXISTS langchain_pg_collection;')
    # op.drop_table('langchain_pg_collection') # Replaced by raw SQL
    # op.drop_index('ix_cmetadata_gin', table_name='langchain_pg_embedding', postgresql_using='gin') # Index dropped by CASCADE
    # op.drop_table('langchain_pg_embedding') # Replaced by raw SQL
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate tables in reverse order of dropping
    op.create_table('langchain_pg_collection',
        sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
        sa.UniqueConstraint('name', name='langchain_pg_collection_name_key')
    )
    op.create_table('langchain_pg_embedding',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='langchain_pg_embedding_pkey')
    )
    op.create_index('ix_cmetadata_gin', 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
