"""add thread_id to message_history

Revision ID: a156152a3f7d
Revises: 96ec8894ea18
Create Date: 2025-05-02 23:23:24.248213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a156152a3f7d'
down_revision = '96ec8894ea18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('thread_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_history', 'thread_id')
    # ### end Alembic commands ###
