"""Add structured_query to MessageHistory

Revision ID: c903716ac541
Revises: a156152a3f7d
Create Date: 2025-05-04 13:28:38.015039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c903716ac541'
down_revision = 'a156152a3f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('langchain_pg_collection')
    # op.drop_index('ix_cmetadata_gin', table_name='langchain_pg_embedding', postgresql_using='gin') # REMOVE OR COMMENT OUT
    # op.drop_table('langchain_pg_embedding') # REMOVE OR COMMENT OUT
    op.add_column('message_history', sa.Column('structured_query', sa.Text(), nullable=True)) # KEEP THIS LINE
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_history', 'structured_query')
    # op.create_table('langchain_pg_embedding', # REMOVE OR COMMENT OUT
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    # sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='langchain_pg_embedding_pkey')
    # )
    # op.create_index('ix_cmetadata_gin', 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_using='gin') # REMOVE OR COMMENT OUT
    # op.create_table('langchain_pg_collection', # REMOVE OR COMMENT OUT
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    # sa.UniqueConstraint('name', name='langchain_pg_collection_name_key')
    # )
    # ### end Alembic commands ###
