"""add llmprovider and modelconfig tables

Revision ID: ca0328b68ed3
Revises: 3b8f6623a8be
Create Date: 2026-02-21 18:36:42.306650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0328b68ed3'
down_revision = '3b8f6623a8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('documents', 'dl_meta',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('llm_providers', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.alter_column('model_configs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('ix_model_configs_is_default', table_name='model_configs')
    op.drop_constraint(None, 'password_reset_requests', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_requests', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint('uq_user_azure_oid', 'users', ['azure_oid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_azure_oid', 'users', type_='unique')
    op.drop_constraint(None, 'password_reset_requests', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_requests', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_index('ix_model_configs_is_default', 'model_configs', ['is_default'], unique=False)
    op.alter_column('model_configs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('llm_providers', 'is_default')
    op.alter_column('documents', 'dl_meta',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
