"""Add docling_json_path column to documents table

Revision ID: d1f95c33c0c1
Revises: 25edf357937d
Create Date: 2025-04-26 22:20:06.457785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f95c33c0c1'
down_revision = '25edf357937d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('docling_json_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'docling_json_path')
    # ### end Alembic commands ###
