"""empty message

Revision ID: d98af8a9b50c
Revises: c903716ac541
Create Date: 2025-05-05 13:51:15.282291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98af8a9b50c'
down_revision = 'c903716ac541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
